<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright © 2024-2025 Paul Tavitian.
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cloud.tavitian</groupId>
        <artifactId>kindlededrm</artifactId>
        <version>13.0.0</version>
    </parent>

    <artifactId>dedrmtools</artifactId>

    <name>Kindle DeDRM Tools</name>
    <description>Tools for removing DRM encryption from Amazon Kindle eBooks.</description>
    <url>https://github.com/themuzzleflare/dedrmtools</url>

    <properties>
        <kindlekey.macos.test.path>**/KindleKeyMacOSTests.java</kindlekey.macos.test.path>
        <kindlekey.windows.test.path>**/KindleKeyWindowsTests.java</kindlekey.windows.test.path>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
        </dependency>

        <dependency>
            <groupId>org.tukaani</groupId>
            <artifactId>xz</artifactId>
        </dependency>

        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform-jpms</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>cloud.tavitian.dedrmtools.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>dedrmtools-mac-compile</id>

            <activation>
                <os>
                    <name>Mac OS X</name>
                </os>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <excludes>
                                <exclude>**/KindleKeyWindows.java</exclude>
                                <exclude>**/Advapi32.java</exclude>
                                <exclude>**/Crypt32.java</exclude>
                                <exclude>**/DATA_BLOB.java</exclude>
                                <exclude>**/Kernel32.java</exclude>
                            </excludes>
                            <testExcludes>
                                <testExclude>${kindlekey.windows.test.path}</testExclude>
                            </testExcludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>dedrmtools-mac-test</id>

            <activation>
                <os>
                    <name>Mac OS X</name>
                </os>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <excludes>
                                <exclude>${kindlekey.windows.test.path}</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>dedrmtools-win-compile</id>

            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <excludes>
                                <exclude>**/KindleKeyMacOS.java</exclude>
                                <exclude>**/SystemProfilerStorageDriveDataTypes.java</exclude>
                                <exclude>**/IORegStorageDriveClasses.java</exclude>
                            </excludes>
                            <testExcludes>
                                <testExclude>${kindlekey.macos.test.path}</testExclude>
                            </testExcludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>dedrmtools-win-test</id>

            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <argLine>--enable-native-access=com.sun.jna</argLine>
                            <excludes>
                                <exclude>${kindlekey.macos.test.path}</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

</project>
